name: EnchantView
main: thebombzen.mods.enchantview.bukkit.EnchantView
version: 2.3.0
commands:
  doesenchantviewexist:
    description: Asks whether EnchantView exists on this server.
    usage: /doesenchantviewexist
